import {
  IconBarbell,
  IconBook2,
  IconBrandAws,
  IconBrandAzure,
  IconBrandCSharp,
  IconBrandDocker,
  IconBrandGithub,
  IconBrandLinkedin,
  IconBrandReact,
  IconBrandTerraform,
  IconBrandVue,
  IconBrandWhatsapp,
  IconDatabase,
  IconDeviceGamepad2,
  IconMail,
  IconMapPin,
  IconPhone,
  IconRobot,
  type Icon,
} from "@tabler/icons-react";
import type { IconId } from "./types";

// Tabler has no dedicated .NET glyph, so the C# mark stands in for the stack.
export const icons: Record<IconId, Icon> = {
  dotnet: IconBrandCSharp,
  react: IconBrandReact,
  docker: IconBrandDocker,
  vue: IconBrandVue,
  azure: IconBrandAzure,
  aws: IconBrandAws,
  opentofu: IconBrandTerraform,
  sql: IconDatabase,
  agentic: IconRobot,
  gaming: IconDeviceGamepad2,
  reading: IconBook2,
  gym: IconBarbell,
  email: IconMail,
  phone: IconPhone,
  whatsapp: IconBrandWhatsapp,
  linkedin: IconBrandLinkedin,
  github: IconBrandGithub,
  location: IconMapPin,
};
